version: '3.8'

services:
  mongo1:
    container_name: mongo1
    image: mongo:7
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - 27018:27017
    volumes:
      - ./init-replica.js:/docker-entrypoint-initdb.d/init-replica.js:ro
  mongo2:
    container_name: mongo2
    image: mongo:7
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - 27019:27017
  mongo3:
    container_name: mongo3
    image: mongo:7
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - 27020:27017